package docgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/arloliu/fuda/cmd/fuda-doc/internal/docutil"
)

// PrintDefaultYAML writes a plain YAML config file with default values for
// all fields across the given struct docs.
func PrintDefaultYAML(docs []StructDoc, w io.Writer, withComments bool) error {
	if len(docs) == 0 {
		_, _ = fmt.Fprintln(w, "# No structs found.")

		return nil
	}

	_, _ = fmt.Fprintln(w, "# Auto-generated default YAML configuration")
	_, _ = fmt.Fprintln(w, "# Generated by fuda-doc --yaml-default")

	for i, doc := range docs {
		if i > 0 {
			_, _ = fmt.Fprintln(w)
		}

		_, _ = fmt.Fprintf(w, "# %s\n", doc.Name)
		writeYAMLFields(w, doc.Fields, 0, withComments)
	}

	return nil
}

func writeYAMLFields(w io.Writer, fields []FieldInfo, indent int, withComments bool) {
	indentStr := strings.Repeat("  ", indent)

	for _, f := range fields {
		if !docutil.IsExported(f.Name) {
			continue
		}

		key := docutil.YAMLKey(&f)
		if key == "-" {
			continue
		}

		// Optionally write a brief comment.
		if withComments && f.Description != "" {
			first := docutil.FirstLine(f.Description)
			_, _ = fmt.Fprintf(w, "%s# %s\n", indentStr, first)
		}

		if len(f.Nested) > 0 {
			_, _ = fmt.Fprintf(w, "%s%s:\n", indentStr, key)
			writeYAMLFields(w, f.Nested, indent+1, withComments)

			continue
		}

		val := docutil.YAMLDefault(&f)
		_, _ = fmt.Fprintf(w, "%s%s: %s\n", indentStr, key, val)
	}
}
